
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class GamePicker extends javax.swing.JFrame {


    /**
     * Creates new form GamePicker
     */
    public GamePicker() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        intermediateButton = new javax.swing.JButton();
        advancedButton = new javax.swing.JButton();
        beginnerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_player = new javax.swing.JTextField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 450, 90, 30);

        intermediateButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        intermediateButton.setText("Intermediate");
        intermediateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                intermediateButtonMouseClicked(evt);
            }
        });
        intermediateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intermediateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(intermediateButton);
        intermediateButton.setBounds(120, 330, 360, 46);

        advancedButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        advancedButton.setText("Advanced");
        advancedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                advancedButtonMouseClicked(evt);
            }
        });
        advancedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advancedButtonActionPerformed(evt);
            }
        });
        getContentPane().add(advancedButton);
        advancedButton.setBounds(120, 390, 360, 50);

        beginnerButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        beginnerButton.setText("Beginner");
        beginnerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beginnerButtonMouseClicked(evt);
            }
        });
        beginnerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginnerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(beginnerButton);
        beginnerButton.setBounds(120, 270, 360, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WORD-SMASHER (1).png"))); // NOI18N
        jLabel1.setText("Word Smasher");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 60, 530, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Enter-Your-Username.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 170, 280, 40);
        getContentPane().add(txt_player);
        txt_player.setBounds(180, 220, 248, 35);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Starry night Image.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 600, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void beginnerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beginnerButtonMouseClicked
       
        if(txt_player.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Player name is required field");
        }
        else
        {
            new TimerForm(1,txt_player.getText()).setVisible(true);
            this.dispose();            
        }
        
        
    }//GEN-LAST:event_beginnerButtonMouseClicked

    private void intermediateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_intermediateButtonMouseClicked
        // TODO add your handling code here:
        if(txt_player.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Player name is required field");
        }
        else
        {
            new TimerForm(2,txt_player.getText()).setVisible(true);
            this.dispose();            
        }
    }//GEN-LAST:event_intermediateButtonMouseClicked

    private void advancedButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_advancedButtonMouseClicked
        // TODO add your handling code here:
        if(txt_player.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Player name is required field");
        }
        else
        {
            new TimerForm(3,txt_player.getText()).setVisible(true);
            this.dispose();            
        };
    }//GEN-LAST:event_advancedButtonMouseClicked

    private void beginnerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginnerButtonActionPerformed
        if(txt_player.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Player name is required field");
        }
        else
        {
            new TimerForm(1,txt_player.getText()).setVisible(true);
            this.dispose();            
        }
    }//GEN-LAST:event_beginnerButtonActionPerformed

    private void intermediateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intermediateButtonActionPerformed
       if(txt_player.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Player name is required field");
        }
        else
        {
            new TimerForm(2,txt_player.getText()).setVisible(true);
            this.dispose();            
        }
    }//GEN-LAST:event_intermediateButtonActionPerformed

    private void advancedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advancedButtonActionPerformed
        if(txt_player.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Player name is required field");
        }
        else
        {
            new TimerForm(3,txt_player.getText()).setVisible(true);
            this.dispose();            
        }
    }//GEN-LAST:event_advancedButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HomePage hm = new HomePage();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePicker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePicker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton advancedButton;
    private javax.swing.JButton beginnerButton;
    private javax.swing.JButton intermediateButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_player;
    // End of variables declaration//GEN-END:variables
}
