/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.event.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import net.proteanit.sql.DbUtils;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
/**
 *
 * @author Toshiba
 */
public class LeaderShiphardcore extends javax.swing.JFrame {
        Connection conn = null;
        PreparedStatement pst,pst1=null;
        ResultSet rs,rs1=null;
    /**
     * Creates new form EmployeeManager
     */
    public LeaderShiphardcore() {
        initComponents();
        conn = dbconnection.connect();
        FetchPlayer();
        setResizable(false);
       
        
    }
    
    
    
    // Player leadership board details fetch here 
    public void FetchPlayer()
    {
        try{
            pst = conn.prepareStatement("select player_name as 'Player Name',game_mode as 'Game Mode',correct_words as 'Correct Words',wrong_words as 'Wrong Words',missed_words as 'Missed Words',score as 'Score' from player_details_hard where id!='' order by score desc ");
            rs=pst.executeQuery();
            sc_table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        sc_table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));
        setMaximumSize(new java.awt.Dimension(700, 420));
        setMinimumSize(new java.awt.Dimension(700, 420));
        setPreferredSize(new java.awt.Dimension(700, 420));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 420));
        getContentPane().setLayout(null);

        sc_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Roll No", "Student Name", "Phone Number", "Gender", "Department"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        });
        sc_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sc_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(sc_table);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(21, 68, 671, 351);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 30, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LEADERBOARD (2).png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 20, 200, 39);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimage (1).png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(460, 20, 30, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimage (1).png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 20, 30, 30);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Starry night Image.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 710, 420);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void sc_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sc_tableMouseClicked
       
        
    }//GEN-LAST:event_sc_tableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 leadermenu lm = new leadermenu();
       lm.setVisible(true);
       this.dispose();   
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-bg       //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeaderShiphardcore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable sc_table;
    // End of variables declaration//GEN-END:variables
}
