/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mohdm
 */
public class leadermenu extends javax.swing.JFrame {

    /**
     * Creates new form leadermenu
     */
    public leadermenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        beginnerButton = new javax.swing.JButton();
        beginnerButton1 = new javax.swing.JButton();
        beginnerButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(710, 430));
        setMinimumSize(new java.awt.Dimension(710, 430));
        setResizable(false);
        setSize(new java.awt.Dimension(710, 430));
        getContentPane().setLayout(null);

        beginnerButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        beginnerButton.setText("Advanced");
        beginnerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beginnerButtonMouseClicked(evt);
            }
        });
        beginnerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginnerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(beginnerButton);
        beginnerButton.setBounds(170, 270, 360, 50);

        beginnerButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        beginnerButton1.setText("Beginner");
        beginnerButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beginnerButton1MouseClicked(evt);
            }
        });
        beginnerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginnerButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(beginnerButton1);
        beginnerButton1.setBounds(170, 130, 360, 50);

        beginnerButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        beginnerButton2.setText("Intermediate");
        beginnerButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beginnerButton2MouseClicked(evt);
            }
        });
        beginnerButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginnerButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(beginnerButton2);
        beginnerButton2.setBounds(170, 200, 360, 50);

        jButton1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 330, 90, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Starry night Image.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(2, 0, 710, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beginnerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beginnerButtonMouseClicked

    }//GEN-LAST:event_beginnerButtonMouseClicked

    private void beginnerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginnerButtonActionPerformed
        LeaderShiphardcore lee = new LeaderShiphardcore();
        lee.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_beginnerButtonActionPerformed

    private void beginnerButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beginnerButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_beginnerButton1MouseClicked

    private void beginnerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginnerButton1ActionPerformed
        LeaderShip le = new LeaderShip();
        le.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_beginnerButton1ActionPerformed

    private void beginnerButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beginnerButton2MouseClicked
     leadershipintermediate lae = new leadershipintermediate();
        lae.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_beginnerButton2MouseClicked

    private void beginnerButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginnerButton2ActionPerformed

    }//GEN-LAST:event_beginnerButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HomePage hm = new HomePage();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(leadermenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(leadermenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(leadermenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(leadermenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new leadermenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton beginnerButton;
    private javax.swing.JButton beginnerButton1;
    private javax.swing.JButton beginnerButton2;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
