
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class TimerForm extends javax.swing.JFrame {
    int time=60,trigger,score;
      GameScreen gx;
      String PlayerName;
      Connection conn = null;
        PreparedStatement pst=null;
        ResultSet rs=null;
        String GameMode;
    /**
     * Creates new form TimerForm
     */
    
    public TimerForm(int i,String Name) {
        
        initComponents();
        trigger=i;      
        PlayerName=Name;
        saveButton.setEnabled(false);
        conn=dbconnection.connect();
        
        if(i==1)
        {
            GameMode="Beginner";
        }
        else if(i==2)
        {
           GameMode="Intermediate";
        }
        else if(i==3)
        {
           GameMode="Advanced";
        }
        else
        {
            GameMode="";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanel = new javax.swing.JPanel();
        secLabel = new javax.swing.JLabel();
        scoreDataLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        correctLabel = new javax.swing.JLabel();
        correctDataLabel = new javax.swing.JLabel();
        wrongLabel = new javax.swing.JLabel();
        wrongDataLabel = new javax.swing.JLabel();
        missedLabel = new javax.swing.JLabel();
        missedDataLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        exitLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        myPanel.setBackground(new java.awt.Color(0, 0, 0));

        secLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        secLabel.setForeground(new java.awt.Color(255, 255, 255));
        secLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secLabel.setText("01:00");
        secLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        scoreDataLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        scoreDataLabel.setForeground(new java.awt.Color(255, 255, 255));
        scoreDataLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreDataLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        scoreLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        scoreLabel.setForeground(new java.awt.Color(255, 255, 255));
        scoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        correctLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        correctLabel.setForeground(new java.awt.Color(255, 255, 255));
        correctLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        correctLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        correctDataLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        correctDataLabel.setForeground(new java.awt.Color(255, 255, 255));
        correctDataLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        correctDataLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        wrongLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        wrongLabel.setForeground(new java.awt.Color(255, 255, 255));
        wrongLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wrongLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        wrongDataLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        wrongDataLabel.setForeground(new java.awt.Color(255, 255, 255));
        wrongDataLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wrongDataLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        missedLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        missedLabel.setForeground(new java.awt.Color(255, 255, 255));
        missedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        missedLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        missedDataLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        missedDataLabel.setForeground(new java.awt.Color(255, 255, 255));
        missedDataLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        missedDataLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        startButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        startButton.setText("START");
        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButtonMouseClicked(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonMouseClicked(evt);
            }
        });

        exitLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setText("X");
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout myPanelLayout = new javax.swing.GroupLayout(myPanel);
        myPanel.setLayout(myPanelLayout);
        myPanelLayout.setHorizontalGroup(
            myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelLayout.createSequentialGroup()
                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanelLayout.createSequentialGroup()
                        .addGap(891, 891, 891)
                        .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(myPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(correctLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(scoreDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(correctDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(wrongDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wrongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(missedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(missedDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(333, 333, 333))
        );
        myPanelLayout.setVerticalGroup(
            myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scoreDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correctLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correctDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(wrongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wrongDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(missedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(missedDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172)
                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseClicked
        // TODO add your handling code here:
                 /*       scoreLabel.setText("");
                        scoreDataLabel.setText("");
                        correctLabel.setText("");
                        correctDataLabel.setText("");
                        wrongLabel.setText("");
                        wrongDataLabel.setText("");
                        missedLabel.setText("");
                        missedDataLabel.setText("");*/
        
        
        if(startButton.isEnabled()){
        startButton.setEnabled(false);
    
        saveButton.setEnabled(false);
      
        switch(trigger){
            case 1:gx=new GameScreen(1);
                   gx.setVisible(true);
                   break;
            case 2:gx=new GameScreen(2);
                   gx.setVisible(true);
                   break;
            default:gx=new GameScreen(3);
                   gx.setVisible(true);
                   break;
        }
         
          
          Timer timer= new Timer();
          TimerTask task = new TimerTask(){
            public void run(){                                             
                  time--;
                    //System.out.println(String.valueOf(time));
                    if(time>=10){
                       secLabel.setText("00:"+time);
                    }
                    else if(time<10 && time >=0) 
                        secLabel.setText("00:0"+time);
                    else
                    {
                        score= 5*gx.right;
                        scoreLabel.setText("SCORE");
                        scoreDataLabel.setText(String.valueOf(score));
                        correctLabel.setText("CORRECT");
                        correctDataLabel.setText(String.valueOf(gx.right));
                        wrongLabel.setText("WRONG");
                        wrongDataLabel.setText(String.valueOf(gx.wrong));
                        missedLabel.setText("MISSED");
                        missedDataLabel.setText(String.valueOf(gx.missed));
                        
                        gx.stopGame=true;
                        
                        gx.dispose();
                       
                       saveButton.setEnabled(true);
                        
                    }                                              
            }  
          };
          timer.scheduleAtFixedRate(task, 0, 1000);
        }
        
    }//GEN-LAST:event_startButtonMouseClicked

    private void saveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseClicked
        // TODO add your handling code here:
        
        
         
        if(saveButton.isEnabled())
        {
            try {                 
                    
                    //score inserting to db
                    if(trigger==1)
                    {
                        pst = conn.prepareStatement("insert into player_details (player_name,game_mode,correct_words,wrong_words,missed_words,score) values ('"+PlayerName+"','"+GameMode+"','"+correctDataLabel.getText()+"','"+wrongDataLabel.getText()+"','"+missedDataLabel.getText()+"','"+scoreDataLabel.getText()+"')");
                        pst.execute();
                        //pst1.close();
                       JOptionPane.showMessageDialog(null,"Score Added Successfully");
                       
                       GamePicker gm = new GamePicker();
                        gm.setVisible(true);
                        this.dispose();
                    }
                    if(trigger==2)
                    {
                        pst = conn.prepareStatement("insert into player_details_intermediate (player_name,game_mode,correct_words,wrong_words,missed_words,score) values ('"+PlayerName+"','"+GameMode+"','"+correctDataLabel.getText()+"','"+wrongDataLabel.getText()+"','"+missedDataLabel.getText()+"','"+scoreDataLabel.getText()+"')");
                        pst.execute();
                        //pst1.close();
                       JOptionPane.showMessageDialog(null,"Score Added Successfully");
                       
                       GamePicker gm = new GamePicker();
                        gm.setVisible(true);
                        this.dispose();
                    }
                    if(trigger==3)
                    {
                        pst = conn.prepareStatement("insert into player_details_hard (player_name,game_mode,correct_words,wrong_words,missed_words,score) values ('"+PlayerName+"','"+GameMode+"','"+correctDataLabel.getText()+"','"+wrongDataLabel.getText()+"','"+missedDataLabel.getText()+"','"+scoreDataLabel.getText()+"')");
                        pst.execute();
                        //pst1.close();
                       JOptionPane.showMessageDialog(null,"Score Added Successfully");
                       
                       GamePicker gm = new GamePicker();
                        gm.setVisible(true);
                        this.dispose();
                    }
                } catch (SQLException ex) {
                    throw new RuntimeException(ex);
                }
            
            
        }
    }//GEN-LAST:event_saveButtonMouseClicked

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        // TODO add your handling code here:
        if(gx!=null)
            gx.dispose();
        HomePage hm= new HomePage();
        hm.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_exitLabelMouseClicked
    
  
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimerForm(1,"").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel correctDataLabel;
    private javax.swing.JLabel correctLabel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel missedDataLabel;
    private javax.swing.JLabel missedLabel;
    private javax.swing.JPanel myPanel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel scoreDataLabel;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel secLabel;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel wrongDataLabel;
    private javax.swing.JLabel wrongLabel;
    // End of variables declaration//GEN-END:variables
}
